name: Toto 4D Draw Checker (Semakan Hadiah Telegram)

on:
  schedule:
    # Berjalan jam 00:00 UTC (8:00 AM MYT) pada hari Isnin, Rabu, Khamis, Ahad
    - cron: '0 0 * * 0,1,3,4'
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kod Repositori
        uses: actions/checkout@v7

      - name: Pasang Persekitaran Python 3.11
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Pasang Pustaka Python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Semak Keputusan Cabutan Terkini & Hantar Ke Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python python_script/toto_11_draw_checker.py